CREATE TABLE __grocery_autocomplete_de_a (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_b (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_c (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_d (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_e (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_f (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_g (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_h (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_i (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_j (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_k (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_l (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_m (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_n (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_o (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_p (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_q (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_r (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_s (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_t (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_u (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_v (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_w (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_x (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_y (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_z (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_de_0 (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_a (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_b (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_c (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_d (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_e (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_f (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_g (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_h (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_i (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_j (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_k (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_l (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_m (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_n (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_o (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_p (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_q (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_r (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_s (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_t (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_u (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_v (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_w (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_x (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_y (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_z (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_de_0 (name TEXT, grocery_id TEXT);
CREATE INDEX __grocery_autocomplete_de_a_index ON __grocery_autocomplete_de_a(name);
CREATE INDEX __grocery_autocomplete_de_b_index ON __grocery_autocomplete_de_b(name);
CREATE INDEX __grocery_autocomplete_de_c_index ON __grocery_autocomplete_de_c(name);
CREATE INDEX __grocery_autocomplete_de_d_index ON __grocery_autocomplete_de_d(name);
CREATE INDEX __grocery_autocomplete_de_e_index ON __grocery_autocomplete_de_e(name);
CREATE INDEX __grocery_autocomplete_de_f_index ON __grocery_autocomplete_de_f(name);
CREATE INDEX __grocery_autocomplete_de_g_index ON __grocery_autocomplete_de_g(name);
CREATE INDEX __grocery_autocomplete_de_h_index ON __grocery_autocomplete_de_h(name);
CREATE INDEX __grocery_autocomplete_de_i_index ON __grocery_autocomplete_de_i(name);
CREATE INDEX __grocery_autocomplete_de_j_index ON __grocery_autocomplete_de_j(name);
CREATE INDEX __grocery_autocomplete_de_k_index ON __grocery_autocomplete_de_k(name);
CREATE INDEX __grocery_autocomplete_de_l_index ON __grocery_autocomplete_de_l(name);
CREATE INDEX __grocery_autocomplete_de_m_index ON __grocery_autocomplete_de_m(name);
CREATE INDEX __grocery_autocomplete_de_n_index ON __grocery_autocomplete_de_n(name);
CREATE INDEX __grocery_autocomplete_de_o_index ON __grocery_autocomplete_de_o(name);
CREATE INDEX __grocery_autocomplete_de_p_index ON __grocery_autocomplete_de_p(name);
CREATE INDEX __grocery_autocomplete_de_q_index ON __grocery_autocomplete_de_q(name);
CREATE INDEX __grocery_autocomplete_de_r_index ON __grocery_autocomplete_de_r(name);
CREATE INDEX __grocery_autocomplete_de_s_index ON __grocery_autocomplete_de_s(name);
CREATE INDEX __grocery_autocomplete_de_t_index ON __grocery_autocomplete_de_t(name);
CREATE INDEX __grocery_autocomplete_de_u_index ON __grocery_autocomplete_de_u(name);
CREATE INDEX __grocery_autocomplete_de_v_index ON __grocery_autocomplete_de_v(name);
CREATE INDEX __grocery_autocomplete_de_w_index ON __grocery_autocomplete_de_w(name);
CREATE INDEX __grocery_autocomplete_de_x_index ON __grocery_autocomplete_de_x(name);
CREATE INDEX __grocery_autocomplete_de_y_index ON __grocery_autocomplete_de_y(name);
CREATE INDEX __grocery_autocomplete_de_z_index ON __grocery_autocomplete_de_z(name);
CREATE INDEX __grocery_autocomplete_de_0_index ON __grocery_autocomplete_de_0(name);
CREATE INDEX __brand_autocomplete_de_a_index ON __brand_autocomplete_de_a(name);
CREATE INDEX __brand_autocomplete_de_b_index ON __brand_autocomplete_de_b(name);
CREATE INDEX __brand_autocomplete_de_c_index ON __brand_autocomplete_de_c(name);
CREATE INDEX __brand_autocomplete_de_d_index ON __brand_autocomplete_de_d(name);
CREATE INDEX __brand_autocomplete_de_e_index ON __brand_autocomplete_de_e(name);
CREATE INDEX __brand_autocomplete_de_f_index ON __brand_autocomplete_de_f(name);
CREATE INDEX __brand_autocomplete_de_g_index ON __brand_autocomplete_de_g(name);
CREATE INDEX __brand_autocomplete_de_h_index ON __brand_autocomplete_de_h(name);
CREATE INDEX __brand_autocomplete_de_i_index ON __brand_autocomplete_de_i(name);
CREATE INDEX __brand_autocomplete_de_j_index ON __brand_autocomplete_de_j(name);
CREATE INDEX __brand_autocomplete_de_k_index ON __brand_autocomplete_de_k(name);
CREATE INDEX __brand_autocomplete_de_l_index ON __brand_autocomplete_de_l(name);
CREATE INDEX __brand_autocomplete_de_m_index ON __brand_autocomplete_de_m(name);
CREATE INDEX __brand_autocomplete_de_n_index ON __brand_autocomplete_de_n(name);
CREATE INDEX __brand_autocomplete_de_o_index ON __brand_autocomplete_de_o(name);
CREATE INDEX __brand_autocomplete_de_p_index ON __brand_autocomplete_de_p(name);
CREATE INDEX __brand_autocomplete_de_q_index ON __brand_autocomplete_de_q(name);
CREATE INDEX __brand_autocomplete_de_r_index ON __brand_autocomplete_de_r(name);
CREATE INDEX __brand_autocomplete_de_s_index ON __brand_autocomplete_de_s(name);
CREATE INDEX __brand_autocomplete_de_t_index ON __brand_autocomplete_de_t(name);
CREATE INDEX __brand_autocomplete_de_u_index ON __brand_autocomplete_de_u(name);
CREATE INDEX __brand_autocomplete_de_v_index ON __brand_autocomplete_de_v(name);
CREATE INDEX __brand_autocomplete_de_w_index ON __brand_autocomplete_de_w(name);
CREATE INDEX __brand_autocomplete_de_x_index ON __brand_autocomplete_de_x(name);
CREATE INDEX __brand_autocomplete_de_y_index ON __brand_autocomplete_de_y(name);
CREATE INDEX __brand_autocomplete_de_z_index ON __brand_autocomplete_de_z(name);
CREATE INDEX __brand_autocomplete_de_0_index ON __brand_autocomplete_de_0(name);
