CREATE TABLE __grocery_autocomplete_en_a (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_b (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_c (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_d (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_e (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_f (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_g (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_h (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_i (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_j (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_k (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_l (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_m (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_n (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_o (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_p (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_q (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_r (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_s (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_t (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_u (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_v (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_w (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_x (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_y (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_z (name TEXT, grocery_id TEXT);
CREATE TABLE __grocery_autocomplete_en_0 (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_a (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_b (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_c (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_d (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_e (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_f (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_g (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_h (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_i (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_j (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_k (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_l (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_m (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_n (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_o (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_p (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_q (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_r (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_s (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_t (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_u (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_v (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_w (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_x (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_y (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_z (name TEXT, grocery_id TEXT);
CREATE TABLE __brand_autocomplete_en_0 (name TEXT, grocery_id TEXT);
CREATE INDEX __grocery_autocomplete_en_a_index ON __grocery_autocomplete_en_a(name);
CREATE INDEX __grocery_autocomplete_en_b_index ON __grocery_autocomplete_en_b(name);
CREATE INDEX __grocery_autocomplete_en_c_index ON __grocery_autocomplete_en_c(name);
CREATE INDEX __grocery_autocomplete_en_d_index ON __grocery_autocomplete_en_d(name);
CREATE INDEX __grocery_autocomplete_en_e_index ON __grocery_autocomplete_en_e(name);
CREATE INDEX __grocery_autocomplete_en_f_index ON __grocery_autocomplete_en_f(name);
CREATE INDEX __grocery_autocomplete_en_g_index ON __grocery_autocomplete_en_g(name);
CREATE INDEX __grocery_autocomplete_en_h_index ON __grocery_autocomplete_en_h(name);
CREATE INDEX __grocery_autocomplete_en_i_index ON __grocery_autocomplete_en_i(name);
CREATE INDEX __grocery_autocomplete_en_j_index ON __grocery_autocomplete_en_j(name);
CREATE INDEX __grocery_autocomplete_en_k_index ON __grocery_autocomplete_en_k(name);
CREATE INDEX __grocery_autocomplete_en_l_index ON __grocery_autocomplete_en_l(name);
CREATE INDEX __grocery_autocomplete_en_m_index ON __grocery_autocomplete_en_m(name);
CREATE INDEX __grocery_autocomplete_en_n_index ON __grocery_autocomplete_en_n(name);
CREATE INDEX __grocery_autocomplete_en_o_index ON __grocery_autocomplete_en_o(name);
CREATE INDEX __grocery_autocomplete_en_p_index ON __grocery_autocomplete_en_p(name);
CREATE INDEX __grocery_autocomplete_en_q_index ON __grocery_autocomplete_en_q(name);
CREATE INDEX __grocery_autocomplete_en_r_index ON __grocery_autocomplete_en_r(name);
CREATE INDEX __grocery_autocomplete_en_s_index ON __grocery_autocomplete_en_s(name);
CREATE INDEX __grocery_autocomplete_en_t_index ON __grocery_autocomplete_en_t(name);
CREATE INDEX __grocery_autocomplete_en_u_index ON __grocery_autocomplete_en_u(name);
CREATE INDEX __grocery_autocomplete_en_v_index ON __grocery_autocomplete_en_v(name);
CREATE INDEX __grocery_autocomplete_en_w_index ON __grocery_autocomplete_en_w(name);
CREATE INDEX __grocery_autocomplete_en_x_index ON __grocery_autocomplete_en_x(name);
CREATE INDEX __grocery_autocomplete_en_y_index ON __grocery_autocomplete_en_y(name);
CREATE INDEX __grocery_autocomplete_en_z_index ON __grocery_autocomplete_en_z(name);
CREATE INDEX __grocery_autocomplete_en_0_index ON __grocery_autocomplete_en_0(name);
CREATE INDEX __brand_autocomplete_en_a_index ON __brand_autocomplete_en_a(name);
CREATE INDEX __brand_autocomplete_en_b_index ON __brand_autocomplete_en_b(name);
CREATE INDEX __brand_autocomplete_en_c_index ON __brand_autocomplete_en_c(name);
CREATE INDEX __brand_autocomplete_en_d_index ON __brand_autocomplete_en_d(name);
CREATE INDEX __brand_autocomplete_en_e_index ON __brand_autocomplete_en_e(name);
CREATE INDEX __brand_autocomplete_en_f_index ON __brand_autocomplete_en_f(name);
CREATE INDEX __brand_autocomplete_en_g_index ON __brand_autocomplete_en_g(name);
CREATE INDEX __brand_autocomplete_en_h_index ON __brand_autocomplete_en_h(name);
CREATE INDEX __brand_autocomplete_en_i_index ON __brand_autocomplete_en_i(name);
CREATE INDEX __brand_autocomplete_en_j_index ON __brand_autocomplete_en_j(name);
CREATE INDEX __brand_autocomplete_en_k_index ON __brand_autocomplete_en_k(name);
CREATE INDEX __brand_autocomplete_en_l_index ON __brand_autocomplete_en_l(name);
CREATE INDEX __brand_autocomplete_en_m_index ON __brand_autocomplete_en_m(name);
CREATE INDEX __brand_autocomplete_en_n_index ON __brand_autocomplete_en_n(name);
CREATE INDEX __brand_autocomplete_en_o_index ON __brand_autocomplete_en_o(name);
CREATE INDEX __brand_autocomplete_en_p_index ON __brand_autocomplete_en_p(name);
CREATE INDEX __brand_autocomplete_en_q_index ON __brand_autocomplete_en_q(name);
CREATE INDEX __brand_autocomplete_en_r_index ON __brand_autocomplete_en_r(name);
CREATE INDEX __brand_autocomplete_en_s_index ON __brand_autocomplete_en_s(name);
CREATE INDEX __brand_autocomplete_en_t_index ON __brand_autocomplete_en_t(name);
CREATE INDEX __brand_autocomplete_en_u_index ON __brand_autocomplete_en_u(name);
CREATE INDEX __brand_autocomplete_en_v_index ON __brand_autocomplete_en_v(name);
CREATE INDEX __brand_autocomplete_en_w_index ON __brand_autocomplete_en_w(name);
CREATE INDEX __brand_autocomplete_en_x_index ON __brand_autocomplete_en_x(name);
CREATE INDEX __brand_autocomplete_en_y_index ON __brand_autocomplete_en_y(name);
CREATE INDEX __brand_autocomplete_en_z_index ON __brand_autocomplete_en_z(name);
CREATE INDEX __brand_autocomplete_en_0_index ON __brand_autocomplete_en_0(name);
